# Generated by Django 5.1 on 2024-09-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundMe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Signup',
        ),
    ]
