# Generated by Django 5.1 on 2024-10-08 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundMe', '0002_rename_user_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaignid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('campaignname', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('goalAmount', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donationid', models.AutoField(primary_key=True, serialize=False)),
                ('donationdate', models.DateField()),
                ('amount', models.FloatField()),
                ('paymentmethod', models.CharField(max_length=255)),
                ('campaignid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundMe.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentdate', models.DateField()),
                ('paymentstatus', models.CharField(max_length=20)),
                ('donationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundMe.donation')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=200)),
                ('staffemail', models.EmailField(max_length=200)),
                ('staffpassword', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('staffphone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=200)),
                ('studentemail', models.EmailField(max_length=200)),
                ('studentpassword', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('studentphone', models.CharField(max_length=15)),
                ('studentaddress', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.AddField(
            model_name='donation',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundMe.student'),
        ),
    ]
