# Generated by Django 5.1 on 2024-10-14 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundMe', '0006_remove_payment_donationid_delete_donation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationid', models.CharField(editable=False, max_length=10, unique=True)),
                ('donationdate', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('paymentmethod', models.CharField(max_length=255)),
                ('campaignid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundMe.campaign')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundMe.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(editable=False, max_length=10, unique=True)),
                ('paymentdate', models.DateField(default=django.utils.timezone.now)),
                ('paymentstatus', models.CharField(max_length=20)),
                ('donationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundMe.donation')),
            ],
        ),
    ]
