# Generated by Django 5.1 on 2024-10-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundMe', '0007_donation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_images/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaignid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
