# Generated by Django 5.1 on 2024-10-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundMe', '0009_alter_campaign_campaignid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='currentFunding',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
